using System.Collections.Immutable;

namespace InterfaceGenerator;

public static class Utils
{
    public static readonly ImmutableHashSet<string> Keywords = ImmutableHashSet.Create(
        "event",
        "object",
        "string",
        "class",
        "namespace",
        "new",
        "null",
        "base",
        "this",
        "void",
        "int",
        "long",
        "float",
        "double",
        "decimal",
        "bool",
        "true",
        "false",
        "if",
        "else",
        "while",
        "for",
        "foreach",
        "in",
        "do",
        "switch",
        "case",
        "break",
        "continue",
        "default",
        "goto",
        "return",
        "try",
        "catch",
        "finally",
        "throw",
        "throws",
        "public",
        "private",
        "protected",
        "internal",
        "static",
        "readonly",
        "volatile",
        "virtual",
        "abstract",
        "override",
        "params",
        "ref",
        "out"
    );
}